### ISSUE TITLE
Use your script in open source software

### ISSUE THREAD

**Issue by B1T0** [richardmleggett/scripts#1]
Hi @richardmleggett ,

first of all thank you for publishing your scripts here!

I am currently working on a pipeline for genome and metagenome alignments. My colleages and me found your script for pcr duplicate removal very useful. That's why we would like to use it in our pipeline. 

Since we want to publish our work here on GitHub we would like to include your script as well. Seeing that you did not include any license information I would like to kindly ask you for your permission to include your script into our repository. Of course we would mention you and this repository in our description.

I am looking forward to your reply.
Tobias

**Comment by richardmleggett** [comment]
Hi Tobias,
Yep, go for it. As long as you attribute it as you suggest, it's absolutely fine.
All the best,
Richard

**Comment by B1T0** [comment]
Thank you very much!
